---
# Adding plugins: https://pre-commit.com/#plugins

repos:

  # general linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: '^assets/fonts/fontawesome-webfont.svg$'
      - id: end-of-file-fixer
        exclude: '^CNAME$'
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.

  # markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        entry: mdl --style .markdownlint.rb

  # css linting
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        entry: yamllint -c .yamllint.yaml .
