name: lint

on:
  pull_request:
    branches: [ gh-pages ] # gh-pages branches is my default branch

jobs:

  markdown-lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1
        with:
          args: './README.md'

  html-lint:
    name: Lint HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.5
        with:
          root: .

  js-lint:
    name: Lint JS files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
