name: lint

on:
  pull_request:
    branches: [ gh-pages ] # gh-pages branches is my default branch

jobs:

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1
        with:
          args: './README.md'

  html-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.5
        with:
          root: .

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint assets/js/main.js assets/js/rl.js # the only files I'd modify
